name: test_make_pages.yml
on: [push]
jobs:
  test_make_pages_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: sudo apt-get install r-base pandoc make fonts-dejavu-extra
      - run: sudo R -e "install.packages(c('rmarkdown','bookdown'));"
      - run: make -i page@gh-pages
      
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: docs