name: test_make_pages.yml
on: [push]
jobs:
  test_make_pages_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      # install R
      - name: Install R
        run: sudo apt-get install r-base pandoc make fonts-dejavu-extra

      # install R packages
      - name: Install R packages
        run: sudo R -e "install.packages(c('rmarkdown','bookdown'));"

      #	Make site
      - name: Make Site
        run: make -i site

      # Deploy site to gh-pages branch
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: docs